# Generated by Django 5.2.9 on 2025-12-19 07:47

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_page', '0002_alter_annoncements_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='annoncements',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='annoncements',
            old_name='published',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='annoncements',
            name='category',
            field=models.CharField(blank=True, choices=[('apartment', 'Kvartira'), ('house', 'Hovli uy'), ('new_building', 'Yangi qurilgan uy'), ('commercial', 'Tijorat bino'), ('land', 'Yer uchastkasi'), ('rent_apartment', 'Ijara kvartira'), ('rent_house', 'Ijara hovli uy')], default='house', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='annoncements',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
