# Generated by Django 5.2.9 on 2025-12-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_page', '0003_alter_annoncements_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncements',
            name='category',
            field=models.CharField(blank=True, choices=[('apartment', 'Kvartira'), ('house', 'Hovli uy'), ('new_building', 'Yangi qurilgan uy'), ('commercial', 'Tijorat bino'), ('land', 'Yer uchastkasi'), ('rent_apartment', 'Ijara kvartira'), ('rent_house', 'Ijara hovli uy')], default='house', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='annoncements',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=50, null=True),
        ),
    ]
