# Generated by Django 5.2.9 on 2025-12-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_page', '0005_alter_annoncements_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/post/'),
        ),
    ]
