# Generated by Django 5.2.9 on 2025-12-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_page', '0006_alter_annoncements_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='annoncements',
            managers=[
            ],
        ),
    ]
