# Generated by Django 5.2.9 on 2025-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_page', '0007_alter_annoncements_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoncements',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
