# Generated by Django 5.2.9 on 2025-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_page', '0002_alter_showpage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/post/'),
        ),
    ]
